[package]
name = "conductor"
version = "0.0.4"
authors = ["Eric Kidd <git@randomhacks.net>"]

description = "Faraday Conductor: Develop and orchestrate multi-pod docker-compose apps"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/faradayio/conductor"
documentation = "https://faradayio.github.io/conductor/"

[features]
# This is just here to keep travis-cargo happy; we don't do anything special
# for nightly Rust.
unstable = []

[[bin]]
name = "conductor"
doc = false

[dependencies]
docker_compose = "0.3.4"
docopt = "0.6.83"
env_logger = "0.3.4"
glob = "0.2.11"
lazy_static = "0.2.1"
log = "0.3.6"
rand = "0.3.14"
regex = "0.1.73"
rustc-serialize = "0.3.19"
shlex = "0.1.1"
