[package]
name = "cage"
version = "0.1.7"
authors = ["Eric Kidd <git@randomhacks.net>",
           "Derek Kastner <dkastner@gmail.com>"]

description = "Develop multi-pod docker-compose apps"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/faradayio/cage"
documentation = "https://docs.rs/cage/"
homepage = "http://cage.faraday.io/"
build = "build.rs"

[features]
# This build of `cage` is our standard, official build.
default = ["default-minimal", "openssl"]

# This build of `cage` relies on nightly Rust features.
unstable = ["unstable-minimal", "openssl", "clippy"]

# OpenSSL causes build problems on less popular platforms, especially for
# our binary builds.  And we only need it for certain advanced features.
# So we allow it to be disabled using:
#
#     cargo build --no-default-features --features default_minimal
openssl = ["hashicorp_vault", "boondock/ssl"]

# You must always enable one of these features or the other to get serde to
# build.
default-minimal = ["serde_codegen", "compose_yml/default"]
unstable-minimal = ["serde_derive", "compose_yml/unstable"]

[[bin]]
name = "cage"
doc = false
test = true

[build-dependencies]
glob = "0.2.11"
includedir_codegen = "0.2.1"
serde_codegen = { version = "0.8", optional = true }

[dependencies]
boondock = { version = "0.0.46", default-features = false }
clap = { version = "2.14.0", features = ["yaml"] }
clippy = { version = "0.0.*", optional = true }
colored = "1.3.1"
compose_yml = { version = "0.0.45", default-features = false }
env_logger = "0.3.4"
error-chain = "0.5.0"
glob = "0.2.11"
handlebars = "0.21.0"
hashicorp_vault = { version = "0.6.1", optional = true }
includedir = "0.2.1"
lazy_static = "0.2.1"
log = "0.3.6"
phf = "0.7.16"
rand = "0.3.14"
rayon = "0.4.2"
regex = "0.1.73"
retry = "0.4.0"
rustc-serialize = "0.3.19"
semver = "0.5.0"
serde = "0.8"
serde_derive = { version = "0.8", optional = true }
serde_yaml = "0.4.1"
shlex = "0.1.1"
url = "1.2.0"
yaml-rust = "0.3.3"
